import { Canvas } from '@react-three/fiber'
import React, { Suspense, useEffect } from 'react'
import { Scene } from '../components/home/Scene'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'

import styles from '../styles/Home.module.scss'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  useEffect(() =>
  {        
      document.body.classList.add("home");
  });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Canvas>
      <ambientLight />
      <directionalLight color="red" intensity={10} />
      <Suspense fallback={null}>
        <Scene />
      </Suspense>
    </Canvas>
    </>
  )
}
