import { useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import ScrollControExample from '../components/scrollcontrols/ScrollControlExample';

import styles from '../styles/Home.module.scss'
import {Suspense} from "react";


export default function Home() {
    useEffect(() =>
    {        
        document.body.classList.add("scrollcontrol");
    });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.scene}>
            <ScrollControExample />
      </div>
    </>
  )
}
